//
//  ResoFacts.swift
//  Offer
//
//  Created by arkos33 on 1/14/25.
//

struct ResoFacts: Codable {
    let aboveGradeFinishedArea: String?
    let accessibilityFeatures: AccessibilityFeaturesType?
    let additionalFeeInfo: String?
    let additionalParcelsDescription: String?
    let appliances: ApplianceType?
    let architecturalStyle: String?
    let atAGlanceFacts: [Fact]?
    let attic: String?
    let availabilityDate: String?
    let bathrooms: Int?
    let bathroomsFloat: Double?
    let bathroomsFull: Int?
    let bathroomsHalf: Int?
    let bathroomsOneQuarter: Int?
    let bathroomsPartial: Int?
    let bathroomsThreeQuarter: Int?
    let basement: String?
    let basementYN: Bool?
    let bedrooms: Int?
    let belowGradeFinishedArea: String?
    let buildingArea: String?
    let buildingAreaSource: String?
    let buildingFeatures: [String]?
    let buildingName: String?
    let builderModel: String?
    let builderName: String?
    let canRaiseHorses: Bool?
    let carportParkingCapacity: Int?
    let cityRegion: String?
    let commonWalls: String?
    let communityFeatures: CommunityFeaturesType?
    let compensationBasedOn: String?
    let constructionMaterials: ConstructionMaterialsType?
    let contingency: String?
    let cooling: CoolingType?
    let cumulativeDaysOnMarket: CumulativeDaysType?
    let daysOnZillow: Int?
    let developmentStatus: String?
    let doorFeatures: DoorFeaturesType?
    let electric: String?
    let elementarySchool: String?
    let elementarySchoolDistrict: String?
    let elevation: Double?
    let elevationUnits: String?
    let entryLevel: Int?
    let entryLocation: String?
    let exteriorFeatures: ExteriorFeaturesType?
    let exclusions: [String]?
    let feesAndDues: FeesAndDuesType?
    let fencing: String?
    let fireplaceFeatures: FireplaceFeaturesType?
    let fireplaces: Int?
    let flooring: FlooringType?
    let foundationArea: Int?
    let foundationDetails: FoundationDetailsType? // Updated type
    let frontageLength: String?
    let frontageType: String?
    let furnished: Bool?
    let garageParkingCapacity: Int?
    let gas: String?
    let greenBuildingVerificationType: GreenBuildingVerificationType?
    let greenEnergyEfficient: [String]?
    let greenEnergyGeneration: GreenEnergyGenerationType?
    let greenIndoorAirQuality: String?
    let greenSustainability: String?
    let greenWaterConservation: String?
    let hasAdditionalParcels: Bool?
    let hasAssociation: Bool?
    let hasAttachedGarage: Bool?
    let hasAttachedProperty: Bool?
    let hasCarport: Bool?
    let hasCooling: Bool?
    let hasElectricOnProperty: Bool?
    let hasFireplace: Bool?
    let hasGarage: Bool?
    let hasHeating: Bool?
    let hasHomeWarranty: Bool?
    let hasLandLease: Bool?
    let hasOpenParking: Bool?
    let hasPetsAllowed: Bool?
    let hasPrivatePool: Bool?
    let hasRentControl: Bool?
    let hasSpa: Bool?
    let hasView: Bool?
    let hasWaterfrontView: Bool?
    let heating: HeatingType?
    let highSchool: String?
    let highSchoolDistrict: String?
    let homeType: String?
    let horseAmenities: String?
    let horseYN: Bool?
    let incomeIncludes: [String]?
    let inclusions: [String]?
    let interiorFeatures: [String]?
    let irrigationWaterRightsAcres: Double?
    let irrigationWaterRightsYN: Bool?
    let isNewConstruction: Bool?
    let isSeniorCommunity: Bool?
    let landLeaseAmount: Int?
    let landLeaseExpirationDate: String?
    let laundryFeatures: [String]?
    let leaseTerm: String?
    let levels: String?
    let listingId: String?
    let listingTerms: ListingTermsType?
    let livingArea: String?
    let livingAreaRange: String?
    let livingAreaRangeUnits: String?
    let livingQuarters: [String: String]?
    let lotFeatures: LotFeaturesType?
    let lotSize: String?
    let lotSizeDimensions: String?
    let mainLevelBathrooms: Int?
    let mainLevelBedrooms: Int?
    let marketingType: String?
    let media: MediaType?
    let middleOrJuniorSchool: String?
    let middleOrJuniorSchoolDistrict: String?
    let municipality: String?
    let numberOfUnitsInCommunity: Int?
    let numberOfUnitsVacant: Int?
    let offerReviewDate: String?
    let onMarketDate: Int?
    let openParkingCapacity: Int?
    let otherEquipment: [String]?
    let otherFacts: OtherFactsType?
    let otherParking: [String]?
    let otherStructures: [String]?
    let ownership: String?
    let ownershipType: String?
    let parcelNumber: String?
    let parkingCapacity: Int?
    let parkingFeatures: ParkingFeaturesType?
    let parkName: String?
    let patioAndPorchFeatures: [String]?
    let petsMaxWeight: Int?
    let poolFeatures: [String]?
    let pricePerSquareFoot: Int?
    let propertyCondition: String?
    let propertySubType: [String]?
    let roadSurfaceType: RoadSurfaceType?
    let roofType: String?
    let rooms: RoomsType?
    let roomTypes: [String]?
    let securityFeatures: [String]?
    let sewer: SewerType?
    let specialListingConditions: String?
    let spaFeatures: SpaFeaturesType?
    let stories: Int?
    let storiesDecimal: Double?
    let storiesTotal: Int?
    let structureType: String?
    let subdivisionName: String?
    let taxAnnualAmount: Int?
    let taxAssessedValue: Int?
    let tenantPays: [String]?
    let topography: String?
    let totalActualRent: Int?
    let utilities: [String]?
    let vegetation: VegetationType?
    let virtualTour: String?
    let view: ViewTypes?
    let waterBodyName: String?
    let waterSource: WaterSourceType?
    let waterView: String?
    let waterViewYN: Bool?
    let waterfrontFeatures: String?
    let windowFeatures: WindowFeaturesType?
    let woodedArea: Double?
    let zoning: String?
    let zoningDescription: String?
}
